server:
  port: 8081

spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false
