server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    vault:
      authentication: TOKEN
      token: "${VAULT_TOKEN}"
      kv:
        backend: "secret"

http:
  signature:
    key-id: "order-service-key"
    private-key-file: "file:./security-keys/private_key.pem"

logging:
  level:
    org.springframework.security: DEBUG
    com.example.httpsignature: DEBUG
