spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mastererickdiaz/wrks-demo-config
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          skip-ssl-validation: false